### ISSUE TITLE
Typo in links

### ISSUE THREAD

**Issue by shark0der** [in-the-beam/laravel-forums-engine#1]
`s/girhub/github/` in this:

> Preinstall following Packages:
> 5.1. https://girhub.com/doctrine/dbal ( no setup needed )
> 5.2. https://girhub.com/in-the-beam/lib-appjs ( setup required )
> 5.3. https://girhub.com/in-the-beam/laravel-backup-commands ( setup required )

**Comment by h-zone** [comment]
fixed, thanks)
